pipeline {
    agent {
        docker {
            image 'node:16-buster-slim'
            args '-p 3000:3000'
            args '--user root'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                sh 'ls -lah'
                input message: 'Finished using the website? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Deploy') {
            steps {
                echo "Installing SCP in Container"
                sh 'whoami'
                sh 'cat /etc/*release'
                sh 'apt update && apt install -y openssh-client'

                echo "Deploying React Apps to AWS EC2..."

                sh 'ls -lah'
                sh 'chmod 400 aws.pem'
                sh '''
                scp -o StrictHostKeyChecking=no -i aws.pem -r build ubuntu@3.80.80.254:/home/ubuntu/
                ssh -o StrictHostKeyChecking=no -i aws.pem ubuntu@3.80.80.254 'ls -lah'
                '''

                echo "Deployment done! Move build folder to /var/www/html"
                sh '''
                ssh -o StrictHostKeyChecking=no -i aws.pem ubuntu@3.80.80.254 "
                    pwd &&
                    ls -lah &&
                    sudo mv /var/www/html /var/www/html_default &&
                    sudo mv /home/ubuntu/build /var/www/html &&
                    sudo chown root.root /var/www/html -Rf &&
                    sudo ls -lah; sudo ls -lah /var/www/html
                "
                '''

                echo "Test and restart nginx"
                sh '''
                ssh -o StrictHostKeyChecking=no -i aws.pem ubuntu@3.80.80.254 'nginx -t && systemctl restart nginx'
                '''

            }
        }
    }
}
