pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the website? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Deploy') {
            steps {
                echo "Installing SCP in Container"
                sh 'whoami'
                sh 'apk add openssh'

                echo "Deploying React Apps to AWS EC2..."

                sh 'ls -lah'
                sh 'chmod 400 aws.pem'
                sh '''
                scp -o StrictHostKeyChecking=no -i aws.pem -r build ubuntu@3.80.80.254:/home/ubuntu/
                ssh -o StrictHostKeyChecking=no -i aws.pem ubuntu@3.80.80.254 'ls -lah'
                '''

                echo "Deployment done! Move build folder to /var/www/html"
                sh '''
                ssh -o StrictHostKeyChecking=no -i aws.pem ubuntu@3.80.80.254 "
                pwd &&
                ls -lah
                sudo mv /var/www/html /var/www/html_default &&
                sudo mv build /var/www/html &&
                sudo ls -lah; sudo ls -lah /var/www/html &&
                "
                '''

                echo "Test and restart nginx"
                sh 'nginx -t && systemctl restart nginx'
                
            }
        }
    }
}
